package com.cn.hnust.pojo;

public enum EventType {
	CLICK,VIEW,SCANCODE_PUSH,SCANCODE_WAITMSG,
	PIC_SYSPHOTO,PIC_PHOTO_OR_ALBUM
	,PIC_WEIXIN,LOCATION_SELECT,
	SUBSCRIBE,UNSUBSCRIBE,SCAN,LOCATION,
	
}
