package com.cn.hnust.pojo;

public class Sign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.signature
     *
     * @mbggenerated
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.timestamp
     *
     * @mbggenerated
     */
    private String timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.nonce
     *
     * @mbggenerated
     */
    private String nonce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.echostr
     *
     * @mbggenerated
     */
    private String echostr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.id
     *
     * @return the value of sign.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.id
     *
     * @param id the value for sign.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.signature
     *
     * @return the value of sign.signature
     *
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.signature
     *
     * @param signature the value for sign.signature
     *
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.timestamp
     *
     * @return the value of sign.timestamp
     *
     * @mbggenerated
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.timestamp
     *
     * @param timestamp the value for sign.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.nonce
     *
     * @return the value of sign.nonce
     *
     * @mbggenerated
     */
    public String getNonce() {
        return nonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.nonce
     *
     * @param nonce the value for sign.nonce
     *
     * @mbggenerated
     */
    public void setNonce(String nonce) {
        this.nonce = nonce == null ? null : nonce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.echostr
     *
     * @return the value of sign.echostr
     *
     * @mbggenerated
     */
    public String getEchostr() {
        return echostr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.echostr
     *
     * @param echostr the value for sign.echostr
     *
     * @mbggenerated
     */
    public void setEchostr(String echostr) {
        this.echostr = echostr == null ? null : echostr.trim();
    }
}